import AxeBuilder from "@axe-core/playwright"
import { expect, test } from "@playwright/test"

test("records a damaged Issue with evidence and preserves its full lifecycle", async ({ page }) => {
  test.setTimeout(90_000)
  await page.goto("/inventory/issues")
  const recordIssue = page.getByRole("button", { name: "Record issue", exact: true })
  const sheet = page.locator('[data-slot="sheet-content"]')
  await expect(async () => {
    if (!await sheet.isVisible()) await recordIssue.click()
    await expect(sheet).toBeVisible({ timeout: 1_000 })
  }).toPass({ timeout: 10_000 })
  await sheet.getByLabel("Project", { exact: true }).selectOption({ label: "Plano West" })
  await sheet.getByLabel("Issue type").selectOption("Damaged")
  await sheet.getByLabel("Priority").selectOption("High")
  await sheet.getByLabel("Short title").fill("E2E cracked glass mirror")
  await sheet.getByLabel("What happened").fill("Crack visible at the lower corner during yard inspection.")
  await sheet.getByLabel("Blocks project readiness").check()
  await sheet.getByLabel("Operator name").fill("Playwright Yard Operator")

  expect(await sheet.getByLabel("Damage photo").evaluate((element) => (element as HTMLInputElement).checkValidity())).toBe(false)
  await sheet.getByLabel("Damage photo").setInputFiles({ name: "mirror-damage.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64") })
  await expect(sheet.getByAltText("Selected damage evidence preview")).toBeVisible()
  await sheet.getByRole("button", { name: "Record Issue", exact: true }).click()
  await expect(sheet).toBeHidden()

  await page.getByLabel("Search Issues").fill("E2E cracked glass mirror")
  await page.locator('a[href^="/inventory/issues/"]:visible').filter({ hasText: "E2E cracked glass mirror" }).first().click()
  await expect(page).toHaveURL(/\/inventory\/issues\//)
  await expect(page.getByText("Complete", { exact: true })).toBeVisible()
  await expect(page.getByAltText("Crack visible at the lower corner during yard inspection.")).toBeVisible()

  const assignment = page.locator('[data-slot="card"]').filter({ hasText: "Names remain historical even after authentication is added." })
  await assignment.getByLabel("Assigned to").fill("Shift Lead")
  await assignment.getByLabel("Acting operator").fill("Playwright Yard Operator")
  await assignment.getByRole("button", { name: "Save assignment" }).click()
  await expect(page.getByText("Shift Lead", { exact: true }).first()).toBeVisible()

  const followUp = page.locator('[data-slot="card"]').filter({ hasText: "Supplier-return preparation belongs here" })
  await followUp.getByLabel("Follow-up comment").fill("Supplier return instructions requested; mirror isolated from active material.")
  await followUp.getByLabel("Operator name").fill("Shift Lead")
  await followUp.getByRole("button", { name: "Add follow-up" }).click()
  await expect(page.getByText("Supplier return instructions requested; mirror isolated from active material.")).toBeVisible()

  let lifecycle = page.locator('[data-slot="card"]').filter({ hasText: "Every status change requires a note and remains in history." })
  await lifecycle.getByLabel("Change status").selectOption("In Progress")
  await lifecycle.getByLabel("Progress note").fill("Return coordination underway.")
  await lifecycle.getByLabel("Operator name").fill("Shift Lead")
  await lifecycle.getByRole("button", { name: "Mark in progress" }).click()
  await expect(page.getByText("In Progress", { exact: true }).first()).toBeVisible()

  lifecycle = page.locator('[data-slot="card"]').filter({ hasText: "Every status change requires a note and remains in history." })
  await lifecycle.getByLabel("Change status").selectOption("Resolved")
  await lifecycle.getByLabel("Resolution note").fill("Damage documented and return material staged.")
  await lifecycle.getByLabel("Operator name").fill("Shift Lead")
  await lifecycle.getByRole("button", { name: "Mark resolved" }).click()
  await expect(page.getByText("Resolved", { exact: true }).first()).toBeVisible()

  lifecycle = page.locator('[data-slot="card"]').filter({ hasText: "Every status change requires a note and remains in history." })
  await lifecycle.getByLabel("Reopen note").fill("Supplier requested an additional field check.")
  await lifecycle.getByLabel("Operator name").fill("Yard Manager")
  await lifecycle.getByRole("button", { name: "Mark open" }).click()
  await expect(page.getByText("Open", { exact: true }).first()).toBeVisible()
  const history = page.locator('[data-slot="card"]').filter({ hasText: "Comments and lifecycle transitions are append-only." })
  await expect(history).toContainText("Return coordination underway.")

  const results = await new AxeBuilder({ page })
    .withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"])
    .analyze()
  expect(results.violations).toEqual([])
})

test("Issue worklist filters are accessible at the current viewport", async ({ page }) => {
  await page.goto("/inventory/issues")
  await expect(page.getByLabel("Search Issues")).toBeVisible()
  await page.getByLabel("Status").selectOption("All statuses")
  await page.getByLabel("Type").selectOption("Damaged")
  await expect.poll(() => new URL(page.url()).searchParams.get("status")).toBe("All statuses")
  await expect.poll(() => new URL(page.url()).searchParams.get("type")).toBe("Damaged")
  const results = await new AxeBuilder({ page })
    .withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"])
    .analyze()
  expect(results.violations).toEqual([])
})
